development:
  adapter: postgresql
  encoding: unicode
  database: gat_registry_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: gat_registry_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: gat_registry_production
  pool: 5
  username: postgres
  password:
